version: '3.8'

services:
  coaudit-frontend:
    image: 13.91.127.73:8082/coaudit-frontend:latest
    container_name: coaudit-frontend
    ports:
      - "4200:80"
    networks:
      - coaudit-networks

  coaudit-backend:
    image: 13.91.127.73:8082/coaudit-backend:latest
    container_name: coaudit-backend
    ports:
      - "8080:8080"
    networks:
      - coaudit-networks
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: coaudit-db
    ports:
      - "5432:5432"
    networks:
      - coaudit-networks
    environment:
      POSTGRES_PASSWORD: nadastage
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  coaudit-networks:
    driver: bridge

volumes:
  db-data:
